import { Base, Action, AnimationBoolean } from "survey-core";
import { SurveyCreatorModel } from "../../creator-base";
import { SidebarPageModel } from "./side-bar-page-model";
import { SidebarHeaderModel } from "./side-bar-header-model";
export declare class SidebarModel extends Base {
    private creator;
    header: SidebarHeaderModel;
    private _expandAction;
    private _collapseAction;
    private _activePage;
    private onSidebarVisibilityChanged;
    private resizeManager;
    pages: Array<SidebarPageModel>;
    _visible: boolean;
    renderedIsVisible: boolean;
    collapsedManually: boolean;
    expandedManually: boolean;
    hasVisiblePages: boolean;
    flyoutMode: boolean;
    activePage: string;
    hideSideBarVisibilityControlActions: boolean;
    sideAreaComponentName: string;
    sideAreaComponentData: any;
    private rootElement;
    private getAnimationOptions;
    private allowFlyoutMode;
    visibilityAnimation: AnimationBoolean;
    set visible(val: boolean);
    get visible(): boolean;
    get flyoutPanelMode(): boolean;
    get closeText(): string;
    getPageById(id: string): SidebarPageModel;
    private createActions;
    private getCurrentHandles;
    private sidebarLocationChangedHandler;
    constructor(creator: SurveyCreatorModel);
    getActivePage(): SidebarPageModel;
    setActivePage(newPage: SidebarPageModel): void;
    getExpandAction(): Action;
    collapseSidebar(): void;
    expandSidebar(): void;
    addPage(id: string, componentName?: string, model?: any, buildActions?: () => Array<Action>): SidebarPageModel;
    updateHasVisiblePages(): void;
    dispose(): void;
    initResizeManager(container: HTMLDivElement): void;
    resetResizeManager(): void;
}
